version: '3.7'

services:
  web-typescript-stg:
    image: registry.gitlab.com/oxdelivery/oxdelivery-frontend-typescript/staging:latest
    container_name: web-typescript-stg
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
      - 8030:3000
    restart: always