export const TrucksUsageTableData = [
  {
    key: 1,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 2,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 3,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 4,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 5,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 6,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 7,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 8,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 9,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 10,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 11,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 12,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 13,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 14,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  },
  {
    key: 15,
    Truck: "RAC 533 H",
    Model: "Hyundai",
    RevenueMade: "120K Rwf",
    RevenueMadePercentage: "+344%",
    CashPaid: "0 Rwf",
    CashPaidPercentage: "+98%",
    Distance: "0 KMs",
    DistancePercentage: "+98%",
    KGPerKM: "0 KGs",
    Weight: "1.5K KGs",
    WeightPercentage: "0%",
    HoursUsed: "0 Hrs",
    HoursUsedPercentage: "-100%"
  }
];
